// This file will be generated by Supabase CLI later
// For now, we'll create a placeholder type

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      games: {
        Row: {
          id: string
          status: 'waiting' | 'active' | 'ended'
          mode: 'lobby' | 'day' | 'night' | 'endgame'
          cycle_number: number
          started_at: string | null
          ended_at: string | null
          winner: 'villagers' | 'werewolves' | null
          host_user_id: string | null
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          status?: 'waiting' | 'active' | 'ended'
          mode?: 'lobby' | 'day' | 'night' | 'endgame'
          cycle_number?: number
          started_at?: string | null
          ended_at?: string | null
          winner?: 'villagers' | 'werewolves' | null
          host_user_id?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          status?: 'waiting' | 'active' | 'ended'
          mode?: 'lobby' | 'day' | 'night' | 'endgame'
          cycle_number?: number
          started_at?: string | null
          ended_at?: string | null
          winner?: 'villagers' | 'werewolves' | null
          host_user_id?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      players: {
        Row: {
          id: string
          game_id: string
          user_id: string
          role_id: string | null
          alive: boolean
          joined: boolean
          ready: boolean
          vote_choice: number
          do_nothing_vote: number
          target_player_id: string | null
          night_action_done: boolean
          doing_night_action: boolean
          effect: string | null
          previous_nominations: string[] | null
          seen_role: boolean
          seen_death: boolean
          seen_new_events: boolean
          seen_night_results: boolean
          seen_endgame: boolean
          death_cycle: number | null
          death_type: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          game_id: string
          user_id: string
          role_id?: string | null
          alive?: boolean
          joined?: boolean
          ready?: boolean
          vote_choice?: number
          do_nothing_vote?: number
          target_player_id?: string | null
          night_action_done?: boolean
          doing_night_action?: boolean
          effect?: string | null
          previous_nominations?: string[] | null
          seen_role?: boolean
          seen_death?: boolean
          seen_new_events?: boolean
          seen_night_results?: boolean
          seen_endgame?: boolean
          death_cycle?: number | null
          death_type?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          game_id?: string
          user_id?: string
          role_id?: string | null
          alive?: boolean
          joined?: boolean
          ready?: boolean
          vote_choice?: number
          do_nothing_vote?: number
          target_player_id?: string | null
          night_action_done?: boolean
          doing_night_action?: boolean
          effect?: string | null
          previous_nominations?: string[] | null
          seen_role?: boolean
          seen_death?: boolean
          seen_new_events?: boolean
          seen_night_results?: boolean
          seen_endgame?: boolean
          death_cycle?: number | null
          death_type?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      roles: {
        Row: {
          id: string
          name: string
          team: 'villagers' | 'werewolves'
          description: string
          short_description: string | null
          has_night_action: boolean
          is_passive: boolean
          order_priority: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          team: 'villagers' | 'werewolves'
          description: string
          short_description?: string | null
          has_night_action?: boolean
          is_passive?: boolean
          order_priority?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          team?: 'villagers' | 'werewolves'
          description?: string
          short_description?: string | null
          has_night_action?: boolean
          is_passive?: boolean
          order_priority?: number
          created_at?: string
        }
      }
      events: {
        Row: {
          id: string
          game_id: string
          type: 'death' | 'lynch' | 'werewolf_kill' | 'info' | 'warning'
          message: string
          cycle_number: number
          created_at: string
        }
        Insert: {
          id?: string
          game_id: string
          type: 'death' | 'lynch' | 'werewolf_kill' | 'info' | 'warning'
          message: string
          cycle_number: number
          created_at?: string
        }
        Update: {
          id?: string
          game_id?: string
          type?: 'death' | 'lynch' | 'werewolf_kill' | 'info' | 'warning'
          message?: string
          cycle_number?: number
          created_at?: string
        }
      }
    }
    Enums: {
      game_status: 'waiting' | 'active' | 'ended'
      game_mode: 'lobby' | 'day' | 'night' | 'endgame'
      player_team: 'villagers' | 'werewolves'
      event_type: 'death' | 'lynch' | 'werewolf_kill' | 'info' | 'warning'
    }
  }
}
